### ISSUE TITLE
Compile error: 'Serial7' was not declared in scope

### ISSUE THREAD

**Issue by benwiley4000** [PO-MIDI-Adapter/midi-adapter-sofware#5]
I've tried on both macOS 10.14 and Ubuntu Linux 18.04, following the wiki steps for Code Upload. Same error happens.

![Screenshot from 2021-06-06 00-10-39](https://user-images.githubusercontent.com/13558253/120912261-a9525180-c65b-11eb-8a79-863a82d47b01.png)

```
In file included from /home/ben/Downloads/arduino-1.8.13/hardware/teensy/avr/libraries/MIDI/src/MIDI.h:35:0,
                 from /home/ben/Documents/Code/midi-adapter-software/po_midi_adapter/po_midi_adapter.ino:1:
po_midi_adapter:13: error: 'Serial7' was not declared in this scope
 MIDI_CREATE_INSTANCE(HardwareSerial, Serial7, MIDI2);
                                      ^
/home/ben/Downloads/arduino-1.8.13/hardware/teensy/avr/libraries/MIDI/src/serialMIDI.h:102:51: note: in definition of macro 'MIDI_CREATE_INSTANCE'
     MIDI_NAMESPACE::SerialMIDI<Type> serial##Name(SerialPort);\
                                                   ^
'Serial7' was not declared in this scope
```

**Comment by HanYangZhao** [comment]
![po_upload_settings](https://user-images.githubusercontent.com/4143538/120912442-11556780-c65d-11eb-9b35-1393660c0fc9.png)

Try with the following settings?

**Comment by benwiley4000** [comment]
Works with those settings! I had teensy 3.6 and serial+midi16. Teensy 4.1
and serial+midi4 works.
